#!/bin/sh /etc/rc.common

START=99

start() {
    if [ -e /etc/checkled ]
    then
        echo "HC is running mode test" > /dev/console
    else
        counter=0
        ntp_success=0
        while true
        do
            ping -c5 www.google.com >/dev/null 2>&1
            status=$?

            if [ $status -eq 0 ]
            then
                /bin/echo "1" > /sys/class/leds/linkit-smart-7688:orange:internet/brightness

                ntpd -q -p 1.openwrt.pool.ntp.org >/tmp/ntp.log 2>&1
                if [ $? -eq 0 ]; then
                    echo "$(date) : NTP sync OK" >> /tmp/ntp.log
                    ntp_success=1
                else
                    echo "$(date) : NTP sync FAIL" >> /tmp/ntp.log
					ntp_success=0
                fi

                if [ $counter -ge 120 ]; then
                    if [ $ntp_success -eq 1 ]; then
                        hwclock -w
                        echo "$(date) : Wrote system time -> RTC" >> /tmp/ntp.log
                        ntp_success=0
                    else
                        echo "$(date) : No successful NTP sync in last hour" >> /tmp/ntp.log
                    fi
                    counter=0
                fi
            else
                /bin/echo "0" > /sys/class/leds/linkit-smart-7688:orange:internet/brightness

                hwclock -s
                echo "$(date) : Sync from RTC (no internet)" >> /tmp/ntp.log
            fi

            counter=$((counter+1))
            sleep 25
        done
    fi
}
