#!/bin/sh /etc/rc.common
START=1
STOP=10

USE_PROCD=1

start_service()
{
        include /lib/functions

        logger "sshrd start"

        procd_open_instance
        procd_set_param command sshrd
        procd_set_param respawn

        procd_set_param stdout 1
        procd_set_param stderr 1

        procd_close_instance
}

stop_service() {
    logger "sshrd stop"
    killall sshrd
}


